kind: pipeline
type: docker
steps:
- name: build
  image: registry.cn-hangzhou.aliyuncs.com/profzone/golang-onbuild:1.14
  pull: always
  commands:
  - cd ./cmd/eden
  - go install
  when:
    branch:
      include:
      - master
- name: ship
  image: registry.cn-hangzhou.aliyuncs.com/profzone/golang-onship:1.14
  pull: always
  commands:
  - docker build -t registry.cn-hangzhou.aliyuncs.com/profzone/golang-onbuild:1.14 -f scripts/onbuild.Dockerfile .
  - docker build -t registry.cn-hangzhou.aliyuncs.com/profzone/golang-onship:1.14 -f scripts/onship.Dockerfile .
  - docker build -t registry.cn-hangzhou.aliyuncs.com/profzone/golang-ondeploy:2.4.3 -f scripts/ondeploy.Dockerfile .
  - docker push registry.cn-hangzhou.aliyuncs.com/profzone/golang-onbuild:1.14
  - docker push registry.cn-hangzhou.aliyuncs.com/profzone/golang-onship:1.14
  - docker push registry.cn-hangzhou.aliyuncs.com/profzone/golang-ondeploy:2.4.3
  when:
    branch:
      include:
      - master
