kind: pipeline
type: docker
steps:
- name: test-build
  image: registry.cn-hangzhou.aliyuncs.com/profzone/golang-onbuild:1.14
  pull: always
  commands:
  - cd ./cmd/eden
  - go install
  when:
    branch:
      include:
      - master
- name: docker
  image: docker:19.03.12-dind
- name: ship
  image: registry.cn-hangzhou.aliyuncs.com/profzone/golang-onship:1.14
  pull: always
  commands:
  - eden ci self-build
  when:
    branch:
      include:
      - master
